# English text as it appears in public/index.html, paired with its Vietnamese translation.
# scripts/build-i18n.py wraps each English occurrence in <span data-i18n="…"> and writes the
# Vietnamese side into public/i18n.js.
LANDING = [
  ('nav.checks', 'What it checks', 'App kiểm tra gì'),
  ('nav.how', 'How it works', 'Cách hoạt động'),
  ('nav.verdicts', 'Verdicts', 'Kết luận'),
  ('nav.scope', 'v0.1 scope', 'Phạm vi v0.1'),
  ('cta.scan', 'Scan a plugin', 'Quét plugin'),
  ('hero.eyebrow', 'v0.1 · static analysis for Claude Code plugins', 'v0.1 · phân tích tĩnh cho plugin Claude Code'),
  ('hero.title', 'Read the mod <em>before</em> it reads your machine.', 'Đọc mod <em>trước khi</em> nó đọc máy của bạn.'),
  ('hero.lede', "Claude Code mods run with the same access as Claude Code itself, with no sandbox. Mod Scanner opens a plugin, lists everything it can do, and points at the line that does something it shouldn't. It never runs the plugin's code.",
   'Mod của Claude Code chạy với đúng quyền của Claude Code, không có sandbox. Mod Scanner mở plugin ra, liệt kê mọi thứ nó làm được và chỉ thẳng vào dòng code làm điều không nên làm. Code của plugin không bao giờ được chạy.'),
  ('hero.primary', 'Scan a GitHub repo or .zip', 'Quét repo GitHub hoặc file .zip'),
  ('hero.secondary', 'See what v0.1 checks', 'Xem v0.1 kiểm tra gì'),
  ('hero.cli', 'Or from a terminal, with a CI-friendly exit code:', 'Hoặc chạy trong terminal, với exit code dùng được cho CI:'),
  ('pin.title', 'Appends extra shell commands to the model’s Bash calls', 'Chèn thêm lệnh shell vào các lệnh Bash của model'),
  ('pin.body', 'The command you approve is not the command that runs: the mod adds its own download-and-execute step.',
   'Lệnh bạn duyệt không phải lệnh được chạy: mod gắn thêm bước tải về rồi thực thi của riêng nó.'),
  ('pin.where', 'hooks/register.tsx:5 · mod.bash-rewrite-inject · verdict: Malicious indicators', 'hooks/register.tsx:5 · mod.bash-rewrite-inject · kết luận: Có dấu hiệu độc hại'),
  ('man.intercepts', 'intercepts', 'chặn'),
  ('man.network', 'network', 'mạng'),
  ('man.none', 'none declared', 'không khai báo'),
  ('proof.1', 'official Anthropic plugins scanned for calibration', 'plugin chính thức của Anthropic đã quét để hiệu chỉnh'),
  ('proof.2', 'of them rated malicious or high risk', 'trong số đó bị đánh giá độc hại hoặc rủi ro cao'),
  ('proof.3', 'test fixtures given the expected verdict', 'mẫu thử cho ra đúng kết luận mong đợi'),
  ('proof.4', 'lines of plugin code executed', 'dòng code của plugin bị chạy'),
  ('cov.eyebrow', 'What v0.1 checks', 'v0.1 kiểm tra gì'),
  ('cov.title', 'Every part a plugin can ship, not only the mod.', 'Mọi thành phần plugin có thể chứa, không chỉ riêng mod.'),
  ('cov.lede', 'A plugin can carry mods, shell hooks, MCP servers, and instructions for the model. Each one can hide a payload, so each one is read with rules written for it.',
   'Một plugin có thể chứa mod, shell hook, MCP server và chỉ dẫn cho model. Thành phần nào cũng có thể giấu mã độc, nên mỗi loại được đọc bằng bộ quy tắc viết riêng cho nó.'),
  ('cov.mods.lede', 'Parsed with the TypeScript compiler. Every call on <code>$</code> is resolved to its path, through aliases like <code>const { fetch: send } = $.http</code> and renamed hook parameters, then traced from where data is read to where it goes.',
   'Phân tích bằng TypeScript compiler. Mọi lời gọi trên <code>$</code> được truy về đúng đường dẫn, kể cả qua alias như <code>const { fetch: send } = $.http</code> hay tham số hook bị đổi tên, rồi lần theo dữ liệu từ chỗ được đọc tới chỗ nó đi ra.'),
  ('c.m1', 'Settings, secret env vars, credential files or the conversation flowing into <code>$.http.fetch</code>, <code>$.process</code> or <code>$.mcp.call</code>',
   'Settings, biến môi trường bí mật, file credential hoặc nội dung hội thoại chảy vào <code>$.http.fetch</code>, <code>$.process</code> hoặc <code>$.mcp.call</code>'),
  ('c.m2', '<code>tool.call</code> hooks that append commands to the model’s Bash calls', 'Hook <code>tool.call</code> chèn thêm lệnh vào các lệnh Bash của model'),
  ('c.m3', '<code>prompt.compose</code> text that tells the model to hide something and insert or send something', 'Nội dung <code>prompt.compose</code> bảo model giấu điều gì đó, đồng thời chèn hoặc gửi đi thứ gì đó'),
  ('c.m4', '<code>tool.check</code> hooks that answer <code>allow</code> for Bash, Write, Edit or MCP tools', 'Hook <code>tool.check</code> tự trả lời <code>allow</code> cho Bash, Write, Edit hoặc tool MCP'),
  ('c.m5', 'Computed <code>$[name]</code> access, <code>eval</code>, <code>new Function</code>, base64 that decodes to a URL or command', 'Truy cập động <code>$[name]</code>, <code>eval</code>, <code>new Function</code>, chuỗi base64 giải mã ra URL hoặc lệnh'),
  ('c.m6', 'Writes to <code>.git/hooks</code>, shell rc files, <code>.claude/settings.json</code>, <code>CLAUDE.md</code>', 'Ghi vào <code>.git/hooks</code>, file rc của shell, <code>.claude/settings.json</code>, <code>CLAUDE.md</code>'),
  ('c.m7', 'Changing <code>NODE_OPTIONS</code>, <code>PATH</code>, <code>ANTHROPIC_BASE_URL</code> and similar for every later command', 'Đổi <code>NODE_OPTIONS</code>, <code>PATH</code>, <code>ANTHROPIC_BASE_URL</code> và các biến tương tự cho mọi lệnh chạy sau'),
  ('c.m8', 'Requests to tunnels, paste sites, webhooks and raw IPs; shell or computed commands', 'Gửi request tới tunnel, trang paste, webhook và IP trần; chạy shell hoặc lệnh ghép lúc chạy'),
  ('c.m9', 'Date checks (time bombs) and CI or sandbox checks used to behave well under analysis', 'Kiểm tra ngày (bom hẹn giờ), kiểm tra CI hay sandbox để giả vờ vô hại khi bị phân tích'),
  ('c.m10', 'Rewriting file edits or URLs; redrawing permission or confirmation UI; minified source', 'Sửa nội dung file hoặc URL; vẽ lại giao diện xin quyền hay xác nhận; code bị minify'),
  ('cov.hooks', 'Shell hooks', 'Shell hook'),
  ('c.h1', 'Download piped into a shell, reverse shells, decode-and-run', 'Tải về rồi đưa thẳng vào shell, reverse shell, giải mã rồi chạy'),
  ('c.h2', 'A command that reads <code>~/.ssh</code> or <code>~/.aws</code> and talks to the network', 'Lệnh vừa đọc <code>~/.ssh</code> hoặc <code>~/.aws</code> vừa gửi dữ liệu ra mạng'),
  ('c.h3', 'Hook scripts that approve permission requests themselves', 'Script hook tự duyệt các yêu cầu cấp quyền'),
  ('c.h4', 'Persistence through cron, launch agents or shell rc files', 'Bám trụ qua cron, launch agent hoặc file rc của shell'),
  ('c.s1', 'Instructions to conceal plus a payload to run, send or insert', 'Chỉ dẫn che giấu kèm một payload để chạy, gửi đi hoặc chèn vào'),
  ('c.s2', 'Hidden HTML comments carrying instructions; zero-width, bidi and tag characters', 'Comment HTML ẩn chứa chỉ dẫn; ký tự zero-width, bidi và tag'),
  ('c.s3', '“Ignore previous instructions”, code-insertion and exfiltration requests', '“Ignore previous instructions”, yêu cầu chèn code và đánh cắp dữ liệu'),
  ('c.s4', '<code>allowed-tools</code> that grants unrestricted Bash', '<code>allowed-tools</code> cấp quyền Bash không giới hạn'),
  ('c.p1', '<code>npx</code> or <code>uvx</code> packages with no pinned version, so every start runs the latest release', 'Package <code>npx</code> hoặc <code>uvx</code> không ghim version, nên mỗi lần khởi động lại chạy bản mới nhất'),
  ('c.p2', 'Remote servers over plain HTTP; servers started through a shell', 'Server từ xa qua HTTP không mã hóa; server được khởi động qua shell'),
  ('cov.files', 'Packages and files', 'Package và file'),
  ('c.f1', '<code>preinstall</code> and <code>postinstall</code> scripts', 'Script <code>preinstall</code> và <code>postinstall</code>'),
  ('c.f2', 'Shipped ELF, Mach-O, PE or WebAssembly binaries', 'File binary ELF, Mach-O, PE hoặc WebAssembly đi kèm'),
  ('caps.title', 'A permission list, written from the code', 'Danh sách quyền, rút ra từ chính code'),
  ('caps.p1', 'Next to the findings, every scan lists what the plugin can do, with the hosts, commands and variables it names. Compare that list with the plugin’s description. A theme that reads your settings and makes network requests needs an explanation.',
   'Bên cạnh các phát hiện, mỗi lần quét đều liệt kê những gì plugin làm được, kèm host, lệnh và biến mà nó nhắc tới. Hãy so danh sách đó với mô tả của plugin. Một theme mà đọc settings của bạn và gửi request ra mạng thì cần được giải thích.'),
  ('caps.p2', 'Each plugin also gets a SHA-256 of its files, so a result is tied to the exact version that was scanned.', 'Mỗi plugin còn có một mã SHA-256 của các file, nên kết quả gắn với đúng phiên bản đã quét.'),
  ('caps.th1', 'Capability', 'Năng lực'),
  ('caps.th2', 'Found from', 'Phát hiện từ'),
  ('caps.th3', 'Example target', 'Ví dụ đối tượng'),
  ('caps.r1', 'Network access', 'Truy cập mạng'),
  ('caps.r2', 'Runs commands', 'Chạy lệnh'),
  ('caps.r3', 'Reads Claude Code settings', 'Đọc settings của Claude Code'),
  ('caps.r4', 'Reads environment', 'Đọc biến môi trường'),
  ('caps.r5', 'Intercepts tool calls', 'Chặn lời gọi tool'),
  ('caps.r6', 'Answers permission prompts', 'Tự trả lời hộp thoại xin quyền'),
  ('caps.r7', 'Changes prompts', 'Sửa prompt'),
  ('how.eyebrow', 'How a scan runs', 'Một lần quét diễn ra thế nào'),
  ('how.title', 'Five steps, all of them reading.', 'Năm bước, bước nào cũng chỉ đọc.'),
  ('how.1t', 'Unpack', 'Giải nén'),
  ('how.1', 'The archive stays in memory. Sizes are checked before anything inflates, so a zip bomb is refused. GitHub archives come only from codeload.github.com.',
   'File nén chỉ nằm trong bộ nhớ. Kích thước được kiểm tra trước khi giải nén nên zip bomb bị từ chối. File từ GitHub chỉ được tải từ codeload.github.com.'),
  ('how.2t', 'Inventory', 'Kiểm kê'),
  ('how.2', 'Find every <code>.claude-plugin/plugin.json</code>, then sort each file by role: mod, shell hook, MCP server, skill, agent, command or script.',
   'Tìm mọi file <code>.claude-plugin/plugin.json</code>, rồi phân loại từng file theo vai trò: mod, shell hook, MCP server, skill, agent, command hay script.'),
  ('how.3t', 'Resolve', 'Truy vết'),
  ('how.3', 'Parse each module, follow aliases back to <code>$</code>, and read hook matchers such as <code>{ tool: \'Bash\' }</code>.',
   'Phân tích từng module, lần theo alias về <code>$</code> và đọc matcher của hook như <code>{ tool: \'Bash\' }</code>.'),
  ('how.4t', 'Trace', 'Theo dòng dữ liệu'),
  ('how.4', 'Mark what comes from sensitive sources and follow it through variables to network, process and file sinks.', 'Đánh dấu dữ liệu từ nguồn nhạy cảm và theo nó qua các biến tới chỗ gửi ra mạng, chạy lệnh hay ghi file.'),
  ('how.5t', 'Score', 'Chấm điểm'),
  ('how.5', 'Weigh findings by severity, damp repeats, lower the severity of quoted examples and unimported test files, then give a verdict.',
   'Tính điểm theo mức độ, giảm trọng số cho lỗi lặp lại, hạ mức với ví dụ trong ngoặc kép và file test không được import, rồi đưa ra kết luận.'),
  ('ver.title', 'Four answers, and none of them is “safe”.', 'Bốn kết luận, và không có kết luận nào là “an toàn”.'),
  ('ver.lede', 'Static analysis can show that something is wrong. It cannot prove that nothing is, so the best result says exactly that.',
   'Phân tích tĩnh có thể chỉ ra chỗ sai. Nó không chứng minh được rằng không có gì sai, nên kết quả tốt nhất chỉ nói đúng như vậy.'),
  ('ver.1', 'Malicious indicators', 'Có dấu hiệu độc hại'),
  ('ver.1r', 'any critical finding', 'có phát hiện mức nghiêm trọng'),
  ('ver.1p', 'Patterns typical of malware. Do not install.', 'Có mẫu điển hình của mã độc. Đừng cài.'),
  ('ver.2', 'High risk', 'Rủi ro cao'),
  ('ver.2r', 'any high finding, or score ≥ 40', 'có phát hiện mức cao, hoặc điểm ≥ 40'),
  ('ver.2p', 'Capabilities that need a close read before installing.', 'Có năng lực cần đọc kỹ trước khi cài.'),
  ('ver.3', 'Review recommended', 'Nên xem lại'),
  ('ver.3r', 'any medium finding, or score ≥ 8', 'có phát hiện mức trung bình, hoặc điểm ≥ 8'),
  ('ver.3p', 'Nothing clearly malicious; some behaviour deserves a look.', 'Không có gì rõ ràng độc hại, nhưng vài hành vi đáng xem lại.'),
  ('ver.4', 'No known issues found', 'Chưa thấy vấn đề đã biết'),
  ('ver.4r', 'otherwise', 'các trường hợp còn lại'),
  ('ver.4p', 'No known pattern in this exact SHA-256.', 'Không có mẫu đã biết nào trong đúng mã SHA-256 này.'),
  ('ver.note', 'The score runs from 0 to 100. Critical findings weigh 60, high 25, medium 8 and low 2. Repeats of the same rule count for less each time, so one noisy rule cannot dominate.',
   'Điểm chạy từ 0 đến 100. Phát hiện nghiêm trọng tính 60, cao 25, trung bình 8, thấp 2. Mỗi lần một quy tắc lặp lại thì được tính ít hơn, nên một quy tắc báo nhiều không lấn át được kết quả.'),
  ('scope.title', 'What this version does, and what it leaves for later.', 'Phiên bản này làm gì, và để lại gì cho sau.'),
  ('scope.in1', '<b>Static analysis</b> of mods, shell hooks, MCP config, skills, agents, commands, scripts and packages', '<b>Phân tích tĩnh</b> mod, shell hook, cấu hình MCP, skill, agent, command, script và package'),
  ('scope.in2', '<b>Capability manifest</b> with hosts, commands, env names and tools for each plugin', '<b>Bản kê năng lực</b> gồm host, lệnh, tên biến môi trường và tool cho từng plugin'),
  ('scope.in3', '<b>Findings</b> with file, line, snippet and rule id; a 0–100 score and a verdict', '<b>Phát hiện</b> kèm file, dòng, đoạn code và mã quy tắc; điểm 0–100 và kết luận'),
  ('scope.in4', '<b>Web app</b>: paste a GitHub URL (repo or folder) or upload a .zip up to 10 MB', '<b>Web app</b>: dán URL GitHub (repo hoặc thư mục) hoặc tải lên file .zip tối đa 10 MB'),
  ('scope.in5', '<b>CLI</b> for folders, zips and GitHub, with JSON output and <code>--fail-on</code> for CI', '<b>CLI</b> cho thư mục, file zip và GitHub, có xuất JSON và <code>--fail-on</code> cho CI'),
  ('scope.in6', '<b>Multi-plugin repos</b>: a marketplace repo gets one report per plugin', '<b>Repo nhiều plugin</b>: repo marketplace có báo cáo riêng cho từng plugin'),
  ('scope.out1', '<b>Sandbox run</b> of a mod against a mocked <code>$</code> with planted fake keys', '<b>Chạy thử trong sandbox</b> với <code>$</code> giả có cài sẵn key giả'),
  ('scope.out2', '<b>LLM review</b> comparing what the code does with what the description promises', '<b>Đánh giá bằng LLM</b>, so những gì code làm với những gì mô tả hứa hẹn'),
  ('scope.out3', '<b>Version diffs</b> that flag a capability added in a later release', '<b>So sánh phiên bản</b> để cảnh báo năng lực mới xuất hiện ở bản sau'),
  ('scope.out4', '<b>Data-flow for Node APIs</b> in MCP servers; they are listed as capabilities only', '<b>Theo dòng dữ liệu cho Node API</b> trong MCP server; hiện chỉ được liệt kê như năng lực'),
  ('scope.out5', '<b>Scope-aware tracing</b>; v0.1 follows variables by name, so deliberate obfuscation can slip past', '<b>Truy vết theo scope</b>; v0.1 theo biến bằng tên, nên code cố tình làm rối có thể lọt qua'),
  ('scope.out6', '<b>A pre-install gate</b> inside Claude Code, and a public database of results', '<b>Chặn trước khi cài</b> ngay trong Claude Code, và cơ sở dữ liệu kết quả công khai'),
  ('close.title', 'Found a plugin you’re not sure about?', 'Gặp một plugin bạn chưa chắc?'),
  ('close.body', 'Paste its GitHub URL. The report shows what it can do and where to look, in a few seconds.', 'Dán URL GitHub của nó. Trong vài giây, báo cáo sẽ cho thấy nó làm được gì và cần xem chỗ nào.'),
  ('foot.1', 'Mod Scanner v0.1 · static analysis only, nothing is executed', 'Mod Scanner v0.1 · chỉ phân tích tĩnh, không chạy bất kỳ code nào'),
  ('foot.2', 'A clean result is not a guarantee of safety. Install mods only from sources you trust.', 'Kết quả sạch không đảm bảo an toàn. Chỉ cài mod từ nguồn bạn tin tưởng.'),
  ('sev.critical', 'Critical', 'Nghiêm trọng'),
  ('sev.high', 'High', 'Cao'),
  ('sev.medium', 'Medium', 'Trung bình'),
  ('scope.inpill', 'In v0.1', 'Có trong v0.1'),
  ('scope.outpill', 'Not yet', 'Chưa có'),
]

SCAN = [
  ('scan.lede', 'Check a Claude Code plugin before you install it. The scan reads the mods, hooks, MCP servers, skills and agents a plugin ships and lists what they can do and anything that looks malicious. Nothing is executed.',
   'Kiểm tra plugin Claude Code trước khi cài. Công cụ đọc mod, hook, MCP server, skill và agent trong plugin, liệt kê những gì chúng làm được và mọi thứ trông có vẻ độc hại. Không có code nào được chạy.'),
  ('scan.tab.github', 'GitHub repository', 'Repo GitHub'),
  ('scan.tab.upload', 'Upload .zip', 'Tải lên .zip'),
  ('scan.url', 'Repository or folder URL', 'URL của repo hoặc thư mục'),
  ('scan.go', 'Scan', 'Quét'),
  ('scan.drop', 'Drop a plugin .zip here', 'Thả file .zip của plugin vào đây'),
  ('scan.drop2', 'or click to choose · up to 10 MB', 'hoặc bấm để chọn · tối đa 10 MB'),
  ('scan.foot', 'Static analysis only. A clean result means no known malicious pattern was found in this exact version (see its SHA-256), not that the plugin is safe. Mods run with the same access as Claude Code itself; install only from sources you trust. Uploaded files are scanned in your browser and never sent to a server.',
   'Chỉ phân tích tĩnh. Kết quả sạch nghĩa là không tìm thấy mẫu độc hại đã biết trong đúng phiên bản này (xem mã SHA-256), không có nghĩa plugin an toàn. Mod chạy với quyền của chính Claude Code; chỉ cài từ nguồn bạn tin tưởng. File bạn tải lên được quét ngay trong trình duyệt và không bao giờ gửi lên server.'),
]
